let placeToVisit:string[] =["china","japan","america","paris","malaysia"];
// console.log(placeToVisit);
// console.log(placeToVisit.sort());
// console.log(placeToVisit);
// console.log(placeToVisit.sort().reverse());
//  console.log(placeToVisit);
// console.log(placeToVisit.reverse());
// console.log(placeToVisit.reverse());
let sortedArray = ["china","japan","america","paris","malaysia"];
sortedArray.sort();
console.log(sortedArray);
sortedArray.reverse();
console.log(sortedArray);
